### ISSUE TITLE
Add support for action.pre, action.post instead of action.main only

### ISSUE THREAD

**Issue by saniales** [JasonEtco/build-and-tag-action#47]
I have an action.yml that looks like this

``` yaml
# ...
runs:
  using: 'node20'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
```

As you can see I need both post and main js files to be included in the action for it to work. However with this I am only limited to main,

How can it be fixed?
